### ISSUE TITLE
Unable to add forums

### ISSUE THREAD

**Issue by jameswill** [Fred89/flatboard#13]
Hi,

I have installed Flatboard 3.0.1 on my test server with PHP 7.0 and Mysql 5.7

I am getting following error on creating forum, by clicking + icon.

**HTTP 404

Oops! The page does not exist :(**

please let me know what I am missing ?

![flatboard_forum](https://user-images.githubusercontent.com/6368036/127672476-1df4b70c-7b0d-4ab4-a0b2-b806eb2a115d.png)

**Comment by Fred89** [comment]
Hi Jameswill,
Try to log out and log back in again. I think you have 2 instances of login on Flatboard.

**Comment by jameswill** [comment]
Hi,

I tried multiple times logging out and logging in again with no success.

**Comment by Fred89** [comment]
Please open init.php and add TRUE on const DEBUG_MODE
Try again more loggin and give your error.log please.

**Comment by jameswill** [comment]
Hi,

I tried setting DEBUG_MODE to TRUE in init.php. However I still can't see "error_log" file  at the path where flatboard in installed. Also my apache logs are empty.

Is there any other way by which I can check my error logs ?

**Comment by Fred89** [comment]
From your Cpanel if you have access ...

**Comment by ashraf21c** [comment]
Hello, the same problem here..
No forum creation... no error log..
i`m using PHP 8.2, Softaculous Installation.
MySQL: 5.7.23-23, Apache Version: 2.4.57.
No error log in installation folder (including subfolders), CPanel reported no errors.
Persmissions: 644 (files), 755 (folders).
Links:
https://prize-sci.org/test3
Administrative URL : https://prize-sci.org/test3/auth.php

I`ll translate Flatboard to Arabic provided that the problem is fixed.
